package networking;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 * HTTP Client utility for interacting with the StrataChess backend API service.
 * <p>
 * Handles player management, game creation, and move registration by translating
 * internal Java domain requests into JSON payloads sent over HTTP.
 */
public class StrataChessAPI {

    /** Base endpoint URL for the backend API service. */
    private static final String BASE_URL = "http://127.0.0.1:8000";

    /** Shared HTTP client instance configured for HTTP/1.1 protocol execution. */
    private static final HttpClient client = HttpClient.newBuilder()
            .version(HttpClient.Version.HTTP_1_1)
            .build();

    // ─────────────────────────────────────────────────────────────────────────────
    // PLAYER MANAGEMENT API
    // ─────────────────────────────────────────────────────────────────────────────

    /**
     * Registers a new player in the database or retrieves an existing player's ID 
     * if the username is already registered (HTTP 409 Conflict).
     *
     * @param username The display name or handle for the player.
     * @return The unique database primary key ID assigned to the player.
     * @throws Exception If an I/O, networking, or JSON parsing error occurs during transmission.
     */
    public static int createPlayer(String username) throws Exception {
        String body = String.format("{\"username\": \"%s\"}", username);
        System.out.println("JSON Payload: " + body);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(BASE_URL + "/players"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .build();

        HttpResponse<String> response =
                client.send(request, HttpResponse.BodyHandlers.ofString());

        System.out.println("\n[API] Status Code: " + response.statusCode());
        System.out.println("[API] Response Body:\n" + response.body());

        // Handle duplicate account creation gracefully by resolving existing ID
        if (response.statusCode() == 409) {
            return getPlayerIdByUsername(username);
        }

        return extractIdFromJson(response.body());
    }

    /**
     * Queries the backend API to look up an existing player's database ID using their username.
     *
     * @param username The unique username to search for.
     * @return The associated player ID from the backend.
     * @throws Exception If the lookup network call fails or parsing encounters malformed JSON.
     */
    private static int getPlayerIdByUsername(String username) throws Exception {
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(BASE_URL + "/players/by-username/" + username))
                .GET()
                .build();

        HttpResponse<String> response =
                client.send(request, HttpResponse.BodyHandlers.ofString());

        System.out.println("[API] Lookup existing player '" + username + "' -> " + response.body());

        return extractIdFromJson(response.body());
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // GAME SESSIONS API
    // ─────────────────────────────────────────────────────────────────────────────

    /**
     * Initializes a new chess match between two designated players in the database.
     *
     * @param whitePlayerId Database ID of the player assigned to White.
     * @param blackPlayerId Database ID of the player assigned to Black.
     * @return The unique game session ID generated by the backend.
     * @throws Exception If the server returns an error or request dispatch fails.
     */
    public static int createGame(int whitePlayerId, int blackPlayerId) throws Exception {
        String body = """
            {
                "white_player_id": %d,
                "black_player_id": %d
            }
            """.formatted(whitePlayerId, blackPlayerId);

        System.out.println("JSON Payload: " + body);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(BASE_URL + "/games"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .build();

        HttpResponse<String> response =
                client.send(request, HttpResponse.BodyHandlers.ofString());

        System.out.println("\n[API] Status Code: " + response.statusCode());
        System.out.println("[API] Response Body:\n" + response.body());

        return extractIdFromJson(response.body());
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // MOVE LOGGING API
    // ─────────────────────────────────────────────────────────────────────────────

    /**
     * Transmits a player's move for validation and persistence in an active game session.
     *
     * @param gameId     The active game session ID.
     * @param playerId   The ID of the player executing the move.
     * @param fromSquare Board starting coordinate in algebraic notation (e.g., "e2").
     * @param toSquare   Board destination coordinate in algebraic notation (e.g., "e4").
     * @param moveNumber Sequential turn index of the move within the match.
     * @param moveType   Classification string describing the move type (e.g., "NORMAL", "CAPTURE", "CASTLE").
     * @return Raw JSON response string from the backend service.
     * @throws Exception If an unhandled network error occurs during execution.
     */
    public static String createMove(int gameId, int playerId, String fromSquare,
                                  String toSquare, int moveNumber, String moveType) throws Exception {

        String body = """
            {
                "player_id": %d,
                "from_square": "%s",
                "to_square": "%s",
                "move_number": %d,
                "move_type": "%s"
            }
            """.formatted(playerId, fromSquare, toSquare, moveNumber, moveType);

        System.out.println("JSON Payload: " + body);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(BASE_URL + "/games/" + gameId + "/moves"))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .build();

        HttpResponse<String> response =
                client.send(request, HttpResponse.BodyHandlers.ofString());

        System.out.println("\n[API] Status Code: " + response.statusCode());
        System.out.println("[API] Response Body:\n" + response.body());

        return response.body();
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // UTILITY METHODS
    // ─────────────────────────────────────────────────────────────────────────────

    /**
     * Extracts the numerical "id" value from a standard single-object JSON response payload.
     * <p>
     * Helper method introduced to centralize string manipulation logic across requests.
     *
     * @param json Raw JSON response string containing an "id" key.
     * @return Parsed primary key integer ID.
     */
    private static int extractIdFromJson(String json) {
        int idStart = json.indexOf("\"id\":") + 5;
        int idEnd = json.indexOf(",", idStart);

        // Fallback boundary handler in case "id" is the final property without trailing comma
        if (idEnd == -1) {
            idEnd = json.indexOf("}", idStart);
        }

        return Integer.parseInt(json.substring(idStart, idEnd).trim());
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // INTEGRATION TEST HARNESS
    // ─────────────────────────────────────────────────────────────────────────────

    /**
     * Execution entry point for validating local end-to-end communication with FastAPI service.
     */
    public static void main(String[] args) throws Exception {
        System.out.println("Testing Java → FastAPI → PostgreSQL Pipeline");

        int whitePlayerId = createPlayer("Daksh");
        int blackPlayerId = createPlayer("Helis");
        System.out.println("White DB Player ID = " + whitePlayerId);
        System.out.println("Black DB Player ID = " + blackPlayerId);

        int gameId = createGame(whitePlayerId, blackPlayerId);
        System.out.println("Created game ID = " + gameId);
    }
}